# Generated by Django 6.1.1 on 2026-09-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("quantity", models.FloatField(default=0.0)),
                ("unit", models.CharField(default="units", max_length=50)),
                ("min_stock_level", models.FloatField(default=10.0)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
