# Generated by Django 6.1.1 on 2026-09-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_inventoryitem"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtest",
            name="reagent_usage_per_test",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="labtest",
            name="required_reagent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.inventoryitem",
            ),
        ),
    ]
